package View;

import Model.LiveMatchManager;
import Model.Team;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 * Created by Baizhong Zhang on 2015/11/24.
 */
public class GameView extends JFrame {
    private JPanel mainPanel;
    private JPanel MainPanel;
    private JPanel LeftPanel;
    private JLabel team1Scores;
    private JLabel team1Point;
    private JLabel team1Foul;
    private JFormattedTextField x1;
    private JFormattedTextField y1;
    private JFormattedTextField z1;
    private JFormattedTextField Team1Name;
    private JPanel RightPanel;
    private JLabel team2Scores;
    private JLabel team2Point;
    private JLabel team2Foul;
    private JFormattedTextField x2;
    private JFormattedTextField y2;
    private JFormattedTextField z2;
    private JFormattedTextField Team2Name;
    private LiveMatchManager teamManager;

    public GameView(LiveMatchManager lmm) throws HeadlessException {
        this.teamManager = lmm;
        ArrayList<Team> teamNames = teamManager.getParticipateTeams();
        String matchTeam1 = teamNames.get(0).getTeamName();
        String matchTeam2 = teamNames.get(1).getTeamName();
        Team1Name.setText(matchTeam1);
        Team2Name.setText(matchTeam2);
    }

    public void getPageView() {
        JFrame frame = new JFrame("GameView");
        frame.setContentPane(new GameView(teamManager).mainPanel);
        //frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
        frame.setSize(300, 400);


    }

    public void addTeamName() {
        ArrayList<Team> teamNames = teamManager.getParticipateTeams();
        String matchTeam1 = teamNames.get(0).getTeamName();
        String matchTeam2 = teamNames.get(1).getTeamName();
        Team1Name = new JFormattedTextField(matchTeam1);
        Team2Name = new JFormattedTextField(matchTeam2);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        MainPanel = new JPanel();
        MainPanel.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(MainPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        LeftPanel = new JPanel();
        LeftPanel.setLayout(new FormLayout("fill:d:noGrow,left:3dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:50px:noGrow,top:4dlu:noGrow,center:68px:noGrow,top:4dlu:noGrow,center:51px:noGrow"));
        MainPanel.add(LeftPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        team1Scores = new JLabel();
        team1Scores.setText("Scores:");
        CellConstraints cc = new CellConstraints();
        LeftPanel.add(team1Scores, cc.xy(1, 3));
        team1Point = new JLabel();
        team1Point.setText("Points:");
        LeftPanel.add(team1Point, cc.xy(1, 5));
        team1Foul = new JLabel();
        team1Foul.setText("Fouls");
        LeftPanel.add(team1Foul, cc.xy(1, 7));
        x1 = new JFormattedTextField();
        LeftPanel.add(x1, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        y1 = new JFormattedTextField();
        LeftPanel.add(y1, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        z1 = new JFormattedTextField();
        LeftPanel.add(z1, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        Team1Name = new JFormattedTextField();
        Team1Name.setFont(new Font("Calibri", Font.BOLD, 22));
        LeftPanel.add(Team1Name, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
        RightPanel = new JPanel();
        RightPanel.setLayout(new FormLayout("fill:d:noGrow,left:3dlu:noGrow,fill:d:grow", "center:max(d;4px):noGrow,top:4dlu:noGrow,center:50px:noGrow,top:4dlu:noGrow,center:68px:noGrow,top:4dlu:noGrow,center:51px:noGrow"));
        MainPanel.add(RightPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        team2Scores = new JLabel();
        team2Scores.setText("Scores:");
        RightPanel.add(team2Scores, cc.xy(1, 3));
        team2Point = new JLabel();
        team2Point.setText("Points:");
        RightPanel.add(team2Point, cc.xy(1, 5));
        team2Foul = new JLabel();
        team2Foul.setText("Fouls");
        RightPanel.add(team2Foul, cc.xy(1, 7));
        x2 = new JFormattedTextField();
        RightPanel.add(x2, cc.xy(3, 3, CellConstraints.FILL, CellConstraints.DEFAULT));
        y2 = new JFormattedTextField();
        RightPanel.add(y2, cc.xy(3, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
        z2 = new JFormattedTextField();
        RightPanel.add(z2, cc.xy(3, 7, CellConstraints.FILL, CellConstraints.DEFAULT));
        Team2Name = new JFormattedTextField();
        Team2Name.setFont(new Font("Calibri", Font.BOLD, 22));
        RightPanel.add(Team2Name, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
